# The tags in this repo are automatically created by lerna and have the format
# @scope/package@0.0.0. Sometimes we need just the semver version, i.e. 0.0.0.

name: Extract version from tag

description: Extracts the semver version from a git tag.

inputs:
  tag:
    description: The git tag
    required: true

outputs:
  version:
    description: The version extracted from the tag
    value: ${{ steps.extract-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Extract version
      id: extract-version
      shell: bash
      run: |
        output=$(./scripts/extract-tag.sh "${{ inputs.tag }}")
        exit_code=$?
        if [ $exit_code -ne 0 ]; then
          echo "$output"
          exit $exit_code
        fi
        echo "version=$output" >> "$GITHUB_OUTPUT"
