# The tags in this repo are automatically created by lerna and have the format
# @scope/package@0.0.0. Sometimes we need just the semver version, i.e. 0.0.0.

name: Extract version from tag

description: Extracts the semver version from a git tag.

inputs:
  tag:
    description: The git tag
    required: true

outputs:
  value:
    description: The version extracted from the tag
    value: ${{ steps.extract-version.outputs.value }}

runs:
  using: composite
  steps:
    - name: Extract version
      id: extract-version
      shell: bash
      run: |
        echo "value=$(./scripts/parse-tag.sh "${{ inputs.tag }}")" >> "$GITHUB_OUTPUT"
