# The tags in this repo are automatically created by lerna and have the format
# @scope/package@0.0.0. Sometimes we need just the semver version, i.e. 0.0.0.

name: Extract version from tag

description: Extracts the semver version from a git tag.

inputs:
  tag:
    description: The git tag
    required: true

outputs:
  version:
    description: The version extracted from the tag
    value: ${{ steps.extract-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Extract version
      id: extract-version
      shell: bash
      run: |
        version=$(./scripts/extract-tag.sh "${{ inputs.tag }}")
        echo "version=$version" >> "$GITHUB_OUTPUT"
        exit_code=$?
        echo "::set-output name=exit-code::$exit_code"
        if [ $exit_code -ne 0 ]; then
          echo "Error: extraction failed with exit code $exit_code"
          exit $exit_code
        fi
