# The tags in this repo are automatically created by lerna and have the format
# @scope/package@0.0.0. Sometimes we need just the semver version, i.e. 0.0.0.

name: Extract version from tag

description: Extracts the semver version from a git tag.

inputs:
  tag:
    description: The git tag
    required: true

outputs:
  version:
    description: The version extracted from the tag
    value: ${{ steps.extract-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Extract version
      id: extract-version
      shell: bash
      run: |
        1="${{ inputs.tag }}"

        validate_input() {
            if [[ ! "$1" =~ ^@[^@]+/[^@]+@[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                echo "Error: Input string must be in the format '@<namespace>/<name>@<semver-version>'"
                exit 1
            fi
        }

        validate_input "$1"

        version=$(echo "$1" | sed 's/.*@[^@]*@\([^@]*\)/\1/')

        echo "version=$version" >> "$GITHUB_OUTPUT"
