services:
  api-server:
    ports:
      - ${PORT}:${PORT}
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    environment:
      - PORT=${PORT}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}
      - CLIENT_OAUTH_URL=${CLIENT_OAUTH_URL}
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
      - TOSHL_CLIENT_ID=${TOSHL_CLIENT_ID}
      - TOSHL_CLIENT_SECRET=${TOSHL_CLIENT_SECRET}

  web-server:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-server
