name: Docker build & push

description: Builds a Docker image and pushes it to a Docker Hub repository.

inputs:
  username:
    description: The username for Docker Hub.
    required: true
  token:
    description: The access token for Docker Hub.
    required: true
  file:
    description: The path to the Dockerfile.
    required: true
  repository:
    description: The name of the repository.
    required: true
  tag:
    description: The tag for the image.
    required: true

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        file: ${{ inputs.file }}
        tags: ${{ inputs.repository }}:${{ inputs.tag }}
