name: 'Echo Input'

description: 'Echoes the input provided to the action'

inputs:
  message:
    description: 'The message to echo'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Echo Message
      shell: bash
      run: echo "${{ inputs.message }}"
