#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Lint commits on main only because that branch triggers the release process
branch="$(git rev-parse --abbrev-ref HEAD)"
if [[ "$branch" = main ]]; then (npx --no -- commitlint --edit ${1}); fi
