name: api - deploy

run-name: "api - deploy: ${{ github.ref_name }}"

on:
  push:
    tags:
      - "@quoll/api@*"
  workflow_dispatch:
    inputs:
      git-tag:
        description: The formatted git tag.
        required: true
        type: string

jobs:
  docker-build-push:
    uses: ./.github/workflows/reuse__docker-build-push.yaml
    with:
      file: packages/api/Dockerfile
      package-name: quoll-api
      git-tag: ${{ github.ref_name }}
    secrets: inherit

  deploy:
    needs: docker-build-push
    uses: ./.github/workflows/reuse__terraform-apply.yaml
    with:
      config-directory-name: "packages/api/terraform"
