name: api - deploy

run-name: "api - deploy: ${{ github.ref_name }}"

on:
  push:
    tags:
      - "@quoll/api@*"
  workflow_dispatch:
    inputs:
      git-tag:
        description: The formatted git tag.
        required: true
        type: string

jobs:
  create-aws-resources:
    uses: ./.github/workflows/reuse__terraform-apply.yaml
    with:
      config-directory-name: "packages/api/terraform"
