name: api - deploy

run-name: "api - deploy: ${{ github.ref_name }}"

on:
  push:
    tags:
      - "@quoll/api@*"
  workflow_dispatch:
    inputs:
      git-tag:
        description: The formatted git tag.
        required: true
        type: string

env:
  AWS_REGION: "us-east-1"

permissions:
  id-token: write

jobs:
  create-aws-resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_GITHUB_OIDC_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}
