name: api - deploy

run-name: "api - deploy: ${{ github.ref_name }}"

on:
  push:
    tags:
      - "@quoll/api@*"
  workflow_dispatch:
    inputs:
      git-tag:
        description: The formatted git tag.
        required: true
        type: string

env:
  AWS_REGION: "us-east-1"
  DOCKER_IMAGE_TAG_PREFIX: quoll-api

permissions:
  id-token: write

jobs:
  create-aws-resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_GITHUB_OIDC_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_ACCOUNT_ID }}
          mask-password: "true"

      - name: Get version
        id: extract-version
        uses: ./.github/actions/extract-version
        with:
          tag: ${{ inputs.git-tag }}

      - name: Make image tag
        id: make-image-tag
        shell: bash
        # e.g. some-package-0.0.1
        run: |
          echo "image-tag=${{ env.DOCKER_IMAGE_TAG_PREFIX }}-${{ steps.extract-version.outputs.version }}" >> "$GITHUB_OUTPUT"
