name: client-mobile - deploy

run-name: "client-mobile - deploy: ${{ github.ref_name }}"

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      git-tag:
        description: The formatted git tag.
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/@quoll/client-mobile@')
    steps:
      - name: Deploy
        shell: bash
        run: echo "Deploying client-mobile..."
