name: Deploy api

on:
  push:
    tags:
      - "@quoll/api@*"

jobs:
  docker-build-push:
    uses: ./.github/reusable-workflows/docker-build-push.yaml
    with:
      file: packages/api/Dockerfile
      package-name: quoll-api
      git-tag: ${{ github.ref_name }}
    secrets: inherit
