name: Deploy client-mobile

run-name: "Deploy client-mobile: ${{ github.ref_name }}"

on:
  push:
    tags:
      - "@quoll/client-mobile@*"
  workflow_dispatch:
    inputs:
      git-tag:
        description: The formatted git tag.
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        shell: bash
        run: echo "Deploying client-mobile..."
