name: Deploy api

on:
  push:
    tags:
      - "@quoll/api@*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the version
        id: version
        uses: ./.github/actions/extract-version
        with:
          tag: ${{ github.ref_name }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: packages/api/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPO }}:quoll-api-${{ steps.version.outputs.version }}
