name: Deploy - client-mobile

run-name: "Deploy - client-mobile: ${{ inputs.git-tag }}"

on:
  workflow_dispatch:
    inputs:
      git-tag:
        description: The formatted git tag.
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(inputs.git-tag, '@quoll/client-mobile@')
    steps:
      - name: Deploy
        shell: bash
        run: echo "Deploying client-mobile..."
