name: Deploy client-web

run-name: Deploy client-web version ${{ github.ref_name }}

on:
  push:
    tags:
      - "@quoll/client-web@*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        shell: bash
        run: echo "Deploying client-web..."
