name: Deploy api

on:
  workflow_dispatch:
  push:
    tags:
      - "@quoll/api@*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: docker build -t api -f packages/api/Dockerfile .
