name: Deploy api

on:
  push:
    tags:
      - "@quoll/api@*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the version from the git tag
        shell: bash
        id: version
        run: |
          echo "value=$(./scripts/parse-tag.sh "${{ github.ref_name }}")" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: packages/api/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPO }}:quoll-api-${{ steps.version.outputs.value }}
