name: Deploy api

on:
  push:
    tags:
      - "@quoll/api@*"
  workflow_dispatch:
    inputs:
      git-tag:
        description: The formatted git tag.
        required: true
        type: string

jobs:
  docker-build-push:
    uses: ./.github/workflows/docker-build-push.yaml
    with:
      file: packages/api/Dockerfile
      package-name: quoll-api
      git-tag: ${{ github.ref_name }}
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Deploy
        shell: bash
        run: echo "Deploying ${{ needs.docker-build-push.outputs.image-tag }} to cloud..."
