name: Docker build & push

on:
  workflow_call:
    inputs:
      file:
        description: The path to the Dockerfile.
        required: true
        type: string
      git-tag:
        description: The formatted git tag.
        required: true
        type: string
      package-name:
        description: The name of the package.
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the version
        id: extract-version
        uses: ./.github/actions/extract-version
        with:
          tag: ${{ inputs.git-tag }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ${{ inputs.file }}
          # e.g. username/repo:some-package-0.0.1
          tags: ${{ secrets.DOCKERHUB_REPO }}:${{ inputs.package-name }}-${{ steps.extract-version.outputs.version }}
