name: "OIDC - plan"

on:
  workflow_dispatch:

jobs:
  docker-build-push:
    uses: ./.github/workflows/terraform-plan.yaml
    with:
      config-directory-name: "./infrastructure"
    secrets: inherit
