name: Publish packages

on: workflow_dispatch

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        uses: ./.github/actions/publish
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
