name: Test workflow

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get the latest version
        shell: bash
        id: version
        run: |
          echo "version=$(./scripts/parse-tag.sh "@quoll/api@23.3.3")" >> "$GITHUB_ENV"
      - name: Run Echo Input Action
        uses: ./.github/actions/echo
        with:
          message: "Version is: $version"
