name: Test workflow

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get the latest version
        id: extract-version
        uses: ./.github/actions/extract-version
        with:
          tag: "@quoll/api@3.4.5"
      - name: Run Echo Input Action
        uses: ./.github/actions/echo
        with:
          message: "Version is: ${{ steps.extract-version.outputs.version }}"
